/* =========================================================================
 * 업무 세트 마스터 — 통합 문서1.xlsx [세트맵] + 세트_선후행_플로우차트.svg 검수 반영 (2026-06-11)
 *   검수 정정: ① HAZ-S3(경영책임자 점검·조치)·RSK-S4(경영책임자 지시조치) 추가 — 엑셀 세트맵 누락분
 *             ② CON-S12 선행 = 세트3·4·9 (플로우차트 화살표 기준)
 * DY_DOC_SET: 문서→세트 키워드 휴리스틱 자동 배정 (TODO: 정식 매핑 시트 수령 시 재생성)
 * ========================================================================= */
window.DY_SETS = [
 {
  "id": "POL-S0",
  "menuKey": "policy",
  "menu": "경영방침",
  "name": "S0 기준문서(절차서)",
  "order": 0,
  "expected": 1,
  "repType": "첨부파일",
  "pre": "",
  "note": ""
 },
 {
  "id": "POL-S1",
  "menuKey": "policy",
  "menu": "경영방침",
  "name": "세트1 목표·경영방침 수립·추진·개선",
  "order": 1,
  "expected": 5,
  "repType": "첨부파일",
  "pre": "세트2(의견청취)",
  "note": ""
 },
 {
  "id": "POL-S2",
  "menuKey": "policy",
  "menu": "경영방침",
  "name": "세트2 종사자 의견청취",
  "order": 2,
  "expected": 2,
  "repType": "첨부파일",
  "pre": "S0",
  "note": "의견청취 대메뉴와 중복 활동"
 },
 {
  "id": "POL-S3",
  "menuKey": "policy",
  "menu": "경영방침",
  "name": "세트3 종사자 공유",
  "order": 3,
  "expected": 2,
  "repType": "첨부파일",
  "pre": "세트1",
  "note": ""
 },
 {
  "id": "ORG-S0",
  "menuKey": "org",
  "menu": "조직",
  "name": "S0 기준문서(규정·기준)",
  "order": 0,
  "expected": 5,
  "repType": "첨부파일",
  "pre": "",
  "note": ""
 },
 {
  "id": "ORG-S1",
  "menuKey": "org",
  "menu": "조직",
  "name": "세트1 전담조직 구성·운영",
  "order": 1,
  "expected": 5,
  "repType": "프로그램",
  "pre": "S0",
  "note": ""
 },
 {
  "id": "ORG-S2",
  "menuKey": "org",
  "menu": "조직",
  "name": "세트2 전문인력 배치·선임",
  "order": 2,
  "expected": 11,
  "repType": "첨부파일",
  "pre": "S0 (세트1과 병렬)",
  "note": ""
 },
 {
  "id": "EXE-S0",
  "menuKey": "comply",
  "menu": "이행관리",
  "name": "S0 인력 배치 현황",
  "order": 0,
  "expected": 1,
  "repType": "프로그램",
  "pre": "",
  "note": ""
 },
 {
  "id": "EXE-S1",
  "menuKey": "comply",
  "menu": "이행관리",
  "name": "세트1 안전보건 예산 편성·집행",
  "order": 1,
  "expected": 4,
  "repType": "프로그램",
  "pre": "S0",
  "note": ""
 },
 {
  "id": "EXE-S2",
  "menuKey": "comply",
  "menu": "이행관리",
  "name": "세트2 관계법령 의무 이행점검",
  "order": 2,
  "expected": 4,
  "repType": "프로그램",
  "pre": "S0 (세트1과 병렬)",
  "note": ""
 },
 {
  "id": "EXE-S3",
  "menuKey": "comply",
  "menu": "이행관리",
  "name": "세트3 경영책임자 지시(인원)",
  "order": 3,
  "expected": 3,
  "repType": "프로그램",
  "pre": "세트1·세트2",
  "note": ""
 },
 {
  "id": "HAZ-S0",
  "menuKey": "hazard",
  "menu": "유해·위험요인 관리",
  "name": "S0 기준문서(절차서)",
  "order": 0,
  "expected": 1,
  "repType": "첨부파일",
  "pre": "",
  "note": ""
 },
 {
  "id": "HAZ-S1",
  "menuKey": "hazard",
  "menu": "유해·위험요인 관리",
  "name": "세트1 유해·위험요인 점검·개선",
  "order": 1,
  "expected": 7,
  "repType": "프로그램",
  "pre": "S0·세트2(측정결과 input)",
  "note": "위험성평가 결과를 input으로 받음"
 },
 {
  "id": "HAZ-S2",
  "menuKey": "hazard",
  "menu": "유해·위험요인 관리",
  "name": "세트2 작업환경측정·유해인자 관리",
  "order": 2,
  "expected": 4,
  "repType": "프로그램",
  "pre": "S0",
  "note": ""
 },
 {
  "id": "HAZ-S3",
  "menuKey": "hazard",
  "menu": "유해·위험요인 관리",
  "name": "세트3 경영책임자 점검·조치",
  "order": 3,
  "expected": 0,
  "repType": "프로그램",
  "pre": "세트1",
  "note": "플로우차트 기준 추가 (엑셀 세트맵 누락)"
 },
 {
  "id": "RSK-S0",
  "menuKey": "risk",
  "menu": "위험성평가",
  "name": "S0 기준문서(절차서·규정)",
  "order": 0,
  "expected": 2,
  "repType": "첨부파일",
  "pre": "",
  "note": ""
 },
 {
  "id": "RSK-S1",
  "menuKey": "risk",
  "menu": "위험성평가",
  "name": "세트1 평가 준비(계획·교육·회의·의견청취)",
  "order": 1,
  "expected": 5,
  "repType": "프로그램",
  "pre": "S0",
  "note": ""
 },
 {
  "id": "RSK-S2",
  "menuKey": "risk",
  "menu": "위험성평가",
  "name": "세트2 위험성평가 실시·결과·공유",
  "order": 2,
  "expected": 24,
  "repType": "프로그램",
  "pre": "세트1",
  "note": ""
 },
 {
  "id": "RSK-S3",
  "menuKey": "risk",
  "menu": "위험성평가",
  "name": "세트3 개선대책·조치 이행",
  "order": 3,
  "expected": 4,
  "repType": "프로그램",
  "pre": "세트2",
  "note": ""
 },
 {
  "id": "RSK-S4",
  "menuKey": "risk",
  "menu": "위험성평가",
  "name": "세트4 경영책임자 지시조치",
  "order": 4,
  "expected": 0,
  "repType": "프로그램",
  "pre": "세트3",
  "note": "플로우차트 기준 추가 (엑셀 세트맵 누락)"
 },
 {
  "id": "RSK-S5",
  "menuKey": "risk",
  "menu": "위험성평가",
  "name": "세트5 관계수급인 위험성평가 연계",
  "order": 5,
  "expected": 4,
  "repType": "프로그램",
  "pre": "세트2 (병렬 연계)",
  "note": "도급관리 세트1과 연계"
 },
 {
  "id": "IMP-S0",
  "menuKey": "improve",
  "menu": "개선조치",
  "name": "S0 기준문서(규정·매뉴얼)",
  "order": 0,
  "expected": 2,
  "repType": "첨부파일",
  "pre": "",
  "note": ""
 },
 {
  "id": "IMP-S1",
  "menuKey": "improve",
  "menu": "개선조치",
  "name": "세트1 재해발생 보고·조사",
  "order": 1,
  "expected": 8,
  "repType": "프로그램",
  "pre": "S0",
  "note": "위험성평가·유해위험 후행(재해 발생 시)"
 },
 {
  "id": "IMP-S2",
  "menuKey": "improve",
  "menu": "개선조치",
  "name": "세트2 재발방지·안전보건진단",
  "order": 2,
  "expected": 6,
  "repType": "프로그램",
  "pre": "세트1",
  "note": ""
 },
 {
  "id": "IMP-S3",
  "menuKey": "improve",
  "menu": "개선조치",
  "name": "세트3 행정처분·시정명령 조치",
  "order": 3,
  "expected": 4,
  "repType": "프로그램",
  "pre": "세트1·세트2 (외부명령 트리거)",
  "note": ""
 },
 {
  "id": "IMP-S4",
  "menuKey": "improve",
  "menu": "개선조치",
  "name": "세트4 안전보건개선계획 수립·시행",
  "order": 4,
  "expected": 5,
  "repType": "프로그램",
  "pre": "세트3 (명령 트리거)",
  "note": ""
 },
 {
  "id": "OPN-S0",
  "menuKey": "opinion",
  "menu": "의견청취",
  "name": "S0 기준문서(절차서·규정·매뉴얼)",
  "order": 0,
  "expected": 5,
  "repType": "첨부파일",
  "pre": "",
  "note": ""
 },
 {
  "id": "OPN-S1",
  "menuKey": "opinion",
  "menu": "의견청취",
  "name": "세트1 종사자 의견청취",
  "order": 1,
  "expected": 5,
  "repType": "프로그램",
  "pre": "S0",
  "note": ""
 },
 {
  "id": "OPN-S2",
  "menuKey": "opinion",
  "menu": "의견청취",
  "name": "세트2 산업안전보건위원회",
  "order": 2,
  "expected": 9,
  "repType": "전자문서",
  "pre": "S0",
  "note": ""
 },
 {
  "id": "OPN-S3",
  "menuKey": "opinion",
  "menu": "의견청취",
  "name": "세트3 노사협의체(협의체)",
  "order": 3,
  "expected": 5,
  "repType": "프로그램",
  "pre": "S0",
  "note": ""
 },
 {
  "id": "OPN-S4",
  "menuKey": "opinion",
  "menu": "의견청취",
  "name": "세트4 근로자대표·건강진단 연계",
  "order": 4,
  "expected": 6,
  "repType": "전자문서",
  "pre": "S0",
  "note": ""
 },
 {
  "id": "OPN-S5",
  "menuKey": "opinion",
  "menu": "의견청취",
  "name": "세트5 경영책임자 지시 이행",
  "order": 5,
  "expected": 3,
  "repType": "프로그램",
  "pre": "세트1~4",
  "note": ""
 },
 {
  "id": "EDU-S0",
  "menuKey": "edu",
  "menu": "안전보건교육",
  "name": "S0 기준·증빙(강사지정·면제·이수증)",
  "order": 0,
  "expected": 5,
  "repType": "첨부파일",
  "pre": "",
  "note": ""
 },
 {
  "id": "EDU-S1",
  "menuKey": "edu",
  "menu": "안전보건교육",
  "name": "세트1 안전보건 계획 수립·이행",
  "order": 1,
  "expected": 5,
  "repType": "전자문서",
  "pre": "S0",
  "note": ""
 },
 {
  "id": "EDU-S2",
  "menuKey": "edu",
  "menu": "안전보건교육",
  "name": "세트2 근로자 정기/채용/변경/특별 교육",
  "order": 2,
  "expected": 23,
  "repType": "전자문서",
  "pre": "세트1",
  "note": ""
 },
 {
  "id": "EDU-S3",
  "menuKey": "edu",
  "menu": "안전보건교육",
  "name": "세트3 관리감독자 교육",
  "order": 3,
  "expected": 2,
  "repType": "전자문서",
  "pre": "세트1",
  "note": ""
 },
 {
  "id": "EDU-S4",
  "menuKey": "edu",
  "menu": "안전보건교육",
  "name": "세트4 안전보건 담당인력 직무교육",
  "order": 4,
  "expected": 5,
  "repType": "전자문서",
  "pre": "세트1",
  "note": ""
 },
 {
  "id": "EDU-S5",
  "menuKey": "edu",
  "menu": "안전보건교육",
  "name": "세트5 교육 이행점검·관리조치",
  "order": 5,
  "expected": 4,
  "repType": "프로그램",
  "pre": "세트2·3·4",
  "note": ""
 },
 {
  "id": "CON-S0",
  "menuKey": "contract",
  "menu": "도급관리",
  "name": "S0 기준문서(매뉴얼·기준·계약서류)",
  "order": 0,
  "expected": 15,
  "repType": "첨부파일",
  "pre": "",
  "note": ""
 },
 {
  "id": "CON-S1",
  "menuKey": "contract",
  "menu": "도급관리",
  "name": "세트1 수급업체 선정·평가",
  "order": 1,
  "expected": 3,
  "repType": "프로그램",
  "pre": "S0",
  "note": ""
 },
 {
  "id": "CON-S2",
  "menuKey": "contract",
  "menu": "도급관리",
  "name": "세트2 안전보건대장 작성·검토",
  "order": 2,
  "expected": 5,
  "repType": "프로그램",
  "pre": "세트1",
  "note": ""
 },
 {
  "id": "CON-S3",
  "menuKey": "contract",
  "menu": "도급관리",
  "name": "세트3 작업장 순회점검",
  "order": 3,
  "expected": 5,
  "repType": "프로그램",
  "pre": "세트2",
  "note": ""
 },
 {
  "id": "CON-S4",
  "menuKey": "contract",
  "menu": "도급관리",
  "name": "세트4 합동 안전보건점검",
  "order": 4,
  "expected": 5,
  "repType": "프로그램",
  "pre": "세트2",
  "note": ""
 },
 {
  "id": "CON-S5",
  "menuKey": "contract",
  "menu": "도급관리",
  "name": "세트5 관계수급인 안전교육 지원",
  "order": 5,
  "expected": 7,
  "repType": "프로그램",
  "pre": "세트1",
  "note": ""
 },
 {
  "id": "CON-S6",
  "menuKey": "contract",
  "menu": "도급관리",
  "name": "세트6 경보체계·대피 훈련",
  "order": 6,
  "expected": 3,
  "repType": "프로그램",
  "pre": "세트1",
  "note": ""
 },
 {
  "id": "CON-S7",
  "menuKey": "contract",
  "menu": "도급관리",
  "name": "세트7 위생시설 지원·애로사항",
  "order": 7,
  "expected": 7,
  "repType": "프로그램",
  "pre": "세트1",
  "note": ""
 },
 {
  "id": "CON-S8",
  "menuKey": "contract",
  "menu": "도급관리",
  "name": "세트8 안전보건정보 문서 제공·점검",
  "order": 8,
  "expected": 8,
  "repType": "프로그램",
  "pre": "세트1",
  "note": ""
 },
 {
  "id": "CON-S9",
  "menuKey": "contract",
  "menu": "도급관리",
  "name": "세트9 작업 조정·안전조치 확인",
  "order": 9,
  "expected": 4,
  "repType": "프로그램",
  "pre": "세트2",
  "note": ""
 },
 {
  "id": "CON-S10",
  "menuKey": "contract",
  "menu": "도급관리",
  "name": "세트10 안전보건관리비",
  "order": 10,
  "expected": 2,
  "repType": "첨부파일",
  "pre": "S0",
  "note": ""
 },
 {
  "id": "CON-S11",
  "menuKey": "contract",
  "menu": "도급관리",
  "name": "세트11 재해예방기술지도",
  "order": 11,
  "expected": 2,
  "repType": "프로그램",
  "pre": "S0",
  "note": ""
 },
 {
  "id": "CON-S12",
  "menuKey": "contract",
  "menu": "도급관리",
  "name": "세트12 경영책임자 점검·지시 이행",
  "order": 12,
  "expected": 4,
  "repType": "프로그램",
  "pre": "세트3·4·9 (점검결과 수렴)",
  "note": ""
 }
];

window.DY_DOC_SET = {
"DOC-001": "POL-S0",
"DOC-002": "POL-S1",
"DOC-003": "POL-S2",
"DOC-004": "POL-S2",
"DOC-005": "POL-S1",
"DOC-006": "POL-S1",
"DOC-007": "POL-S1",
"DOC-008": "POL-S1",
"DOC-009": "POL-S3",
"DOC-010": "POL-S3",
"DOC-011": "ORG-S0",
"DOC-012": "ORG-S1",
"DOC-013": "ORG-S1",
"DOC-014": "ORG-S1",
"DOC-015": "ORG-S1",
"DOC-016": "ORG-S1",
"DOC-017": "HAZ-S0",
"DOC-018": "HAZ-S1",
"DOC-019": "HAZ-S1",
"DOC-020": "HAZ-S1",
"DOC-021": "HAZ-S1",
"DOC-022": "HAZ-S3",
"DOC-023": "HAZ-S3",
"DOC-024": "HAZ-S3",
"DOC-025": "RSK-S0",
"DOC-026": "RSK-S2",
"DOC-027": "RSK-S3",
"DOC-028": "RSK-S3",
"DOC-029": "RSK-S4",
"DOC-030": "RSK-S4",
"DOC-031": "RSK-S4",
"DOC-032": "RSK-S2",
"DOC-033": "EXE-S1",
"DOC-034": "EXE-S1",
"DOC-035": "EXE-S1",
"DOC-036": "EXE-S1",
"DOC-037": "EXE-S0",
"DOC-038": "EXE-S3",
"DOC-039": "EXE-S3",
"DOC-040": "EXE-S3",
"DOC-041": "ORG-S0",
"DOC-043": "ORG-S0",
"DOC-047": "ORG-S0",
"DOC-048": "ORG-S2",
"DOC-049": "ORG-S2",
"DOC-050": "EDU-S4",
"DOC-053": "OPN-S0",
"DOC-054": "OPN-S1",
"DOC-055": "OPN-S1",
"DOC-056": "OPN-S1",
"DOC-057": "OPN-S1",
"DOC-058": "OPN-S5",
"DOC-059": "OPN-S5",
"DOC-060": "OPN-S5",
"DOC-061": "OPN-S5",
"DOC-062": "OPN-S0",
"DOC-063": "OPN-S2",
"DOC-064": "OPN-S2",
"DOC-065": "OPN-S2",
"DOC-066": "OPN-S2",
"DOC-067": "OPN-S2",
"DOC-077": "ORG-S0",
"DOC-078": "CON-S1",
"DOC-079": "CON-S0",
"DOC-080": "CON-S0",
"DOC-081": "CON-S0",
"DOC-082": "CON-S0",
"DOC-083": "CON-S12",
"DOC-084": "CON-S0",
"DOC-085": "CON-S12",
"DOC-086": "CON-S12",
"DOC-087": "CON-S12",
"DOC-088": "CON-S12",
"DOC-089": "IMP-S0",
"DOC-090": "IMP-S1",
"DOC-091": "IMP-S0",
"DOC-092": "IMP-S1",
"DOC-093": "IMP-S2",
"DOC-094": "RSK-S2",
"DOC-095": "IMP-S1",
"DOC-096": "IMP-S3",
"DOC-097": "IMP-S3",
"DOC-098": "IMP-S3",
"DOC-099": "IMP-S3",
"DOC-100": "EXE-S2",
"DOC-101": "EXE-S2",
"DOC-102": "EXE-S2",
"DOC-103": "EXE-S2",
"DOC-104": "EDU-S5",
"DOC-105": "EDU-S5",
"DOC-106": "EDU-S5",
"DOC-107": "EDU-S5",
"DOC-109": "EDU-S1",
"DOC-110": "EDU-S1",
"DOC-113": "EDU-S1",
"DOC-114": "EDU-S1",
"DOC-115": "EDU-S1",
"DOC-116": "ORG-S2",
"DOC-117": "ORG-S2",
"DOC-118": "ORG-S2",
"DOC-119": "ORG-S2",
"DOC-120": "ORG-S2",
"DOC-121": "ORG-S2",
"DOC-122": "ORG-S2",
"DOC-123": "ORG-S2",
"DOC-124": "OPN-S0",
"DOC-125": "OPN-S2",
"DOC-126": "OPN-S2",
"DOC-127": "OPN-S2",
"DOC-128": "OPN-S2",
"DOC-129": "ORG-S0",
"DOC-130": "OPN-S0",
"DOC-131": "ORG-S0",
"DOC-132": "ORG-S0",
"DOC-133": "ORG-S0",
"DOC-134": "ORG-S0",
"DOC-135": "EDU-S0",
"DOC-136": "EDU-S0",
"DOC-137": "EDU-S2",
"DOC-138": "EDU-S0",
"DOC-139": "EDU-S2",
"DOC-140": "EDU-S2",
"DOC-141": "EDU-S2",
"DOC-142": "EDU-S0",
"DOC-143": "EDU-S0",
"DOC-144": "EDU-S2",
"DOC-145": "EDU-S2",
"DOC-146": "EDU-S2",
"DOC-147": "EDU-S0",
"DOC-148": "EDU-S2",
"DOC-149": "EDU-S2",
"DOC-150": "EDU-S0",
"DOC-151": "EDU-S0",
"DOC-152": "EDU-S3",
"DOC-153": "EDU-S3",
"DOC-154": "EDU-S3",
"DOC-155": "EDU-S3",
"DOC-156": "EDU-S3",
"DOC-157": "EDU-S3",
"DOC-158": "EDU-S3",
"DOC-159": "EDU-S3",
"DOC-160": "EDU-S0",
"DOC-161": "EDU-S2",
"DOC-162": "EDU-S2",
"DOC-164": "ORG-S0",
"DOC-165": "EDU-S4",
"DOC-166": "EDU-S0",
"DOC-167": "EDU-S4",
"DOC-168": "EDU-S0",
"DOC-169": "EDU-S4",
"DOC-170": "EDU-S0",
"DOC-172": "OPN-S4",
"DOC-173": "OPN-S4",
"DOC-174": "OPN-S4",
"DOC-175": "RSK-S0",
"DOC-176": "RSK-S2",
"DOC-177": "RSK-S1",
"DOC-178": "RSK-S1",
"DOC-179": "RSK-S1",
"DOC-180": "RSK-S1",
"DOC-181": "RSK-S2",
"DOC-182": "RSK-S3",
"DOC-183": "RSK-S3",
"DOC-184": "RSK-S2",
"DOC-185": "RSK-S2",
"DOC-186": "RSK-S3",
"DOC-187": "RSK-S3",
"DOC-188": "RSK-S2",
"DOC-189": "RSK-S2",
"DOC-190": "RSK-S3",
"DOC-191": "RSK-S3",
"DOC-192": "RSK-S2",
"DOC-193": "RSK-S2",
"DOC-194": "RSK-S3",
"DOC-195": "RSK-S3",
"DOC-196": "RSK-S2",
"DOC-197": "RSK-S2",
"DOC-198": "RSK-S3",
"DOC-199": "RSK-S3",
"DOC-200": "RSK-S2",
"DOC-203": "RSK-S5",
"DOC-204": "RSK-S5",
"DOC-205": "RSK-S5",
"DOC-206": "RSK-S5",
"DOC-216": "IMP-S1",
"DOC-217": "HAZ-S1",
"DOC-229": "HAZ-S1",
"DOC-272": "HAZ-S2",
"DOC-273": "HAZ-S2",
"DOC-274": "HAZ-S2",
"DOC-295": "OPN-S4",
"DOC-296": "OPN-S4",
"DOC-297": "OPN-S4",
"DOC-313": "HAZ-S2",
"DOC-314": "IMP-S1",
"DOC-315": "IMP-S1",
"DOC-316": "IMP-S1",
"DOC-317": "IMP-S1",
"DOC-318": "IMP-S1",
"DOC-319": "IMP-S3",
"DOC-320": "IMP-S2",
"DOC-321": "IMP-S4",
"DOC-322": "IMP-S2",
"DOC-323": "IMP-S2",
"DOC-324": "IMP-S4",
"DOC-325": "IMP-S4",
"DOC-326": "IMP-S4",
"DOC-327": "IMP-S4",
"DOC-328": "IMP-S4",
"DOC-329": "IMP-S1",
"DOC-330": "IMP-S1",
"DOC-331": "IMP-S1",
"DOC-332": "IMP-S1",
"DOC-333": "IMP-S1",
"DOC-334": "IMP-S1",
"DOC-335": "IMP-S3",
"DOC-336": "IMP-S3",
"DOC-337": "IMP-S3",
"DOC-338": "CON-S0",
"DOC-340": "CON-S0",
"DOC-341": "CON-S3",
"DOC-342": "CON-S3",
"DOC-343": "CON-S3",
"DOC-344": "CON-S3",
"DOC-345": "CON-S3",
"DOC-346": "OPN-S0",
"DOC-347": "OPN-S3",
"DOC-348": "OPN-S3",
"DOC-349": "OPN-S3",
"DOC-350": "OPN-S3",
"DOC-351": "OPN-S3",
"DOC-352": "CON-S5",
"DOC-353": "CON-S5",
"DOC-354": "CON-S5",
"DOC-355": "CON-S5",
"DOC-356": "CON-S5",
"DOC-357": "CON-S5",
"DOC-358": "CON-S5",
"DOC-359": "CON-S0",
"DOC-360": "CON-S6",
"DOC-361": "CON-S6",
"DOC-362": "CON-S6",
"DOC-363": "CON-S7",
"DOC-364": "CON-S7",
"DOC-365": "CON-S7",
"DOC-366": "CON-S7",
"DOC-367": "CON-S7",
"DOC-368": "CON-S7",
"DOC-369": "CON-S7",
"DOC-370": "CON-S9",
"DOC-371": "CON-S9",
"DOC-372": "CON-S9",
"DOC-373": "CON-S9",
"DOC-374": "CON-S4",
"DOC-375": "CON-S4",
"DOC-376": "CON-S4",
"DOC-377": "CON-S4",
"DOC-378": "CON-S4",
"DOC-379": "CON-S8",
"DOC-380": "CON-S8",
"DOC-381": "CON-S8",
"DOC-382": "CON-S12",
"DOC-383": "CON-S12",
"DOC-384": "CON-S8",
"DOC-385": "CON-S8",
"DOC-386": "CON-S8",
"DOC-387": "CON-S2",
"DOC-388": "CON-S2",
"DOC-389": "CON-S0",
"DOC-390": "CON-S2",
"DOC-391": "CON-S0",
"DOC-392": "CON-S2",
"DOC-393": "CON-S2",
"DOC-394": "CON-S0",
"DOC-395": "CON-S0",
"DOC-401": "CON-S10",
"DOC-402": "CON-S10",
"DOC-403": "CON-S11",
"DOC-404": "CON-S11",
"DOC-406": "CON-S11",
"DOC-420": "CON-S0",
"DOC-421": "CON-S0"
};
